package pl.agh.edu.kis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-05T09:20:57.450+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://kis.edu.agh.pl/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebMethod
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.GetAllStudentsResponse")
    @WebResult(name = "studentList", targetNamespace = "")
    public pl.agh.edu.kis.GetAllStudentsResponse.StudentList getAllStudents();

    @WebMethod(operationName = "HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.HelloWorldResponse")
    @WebResult(name = "HelloElement", targetNamespace = "")
    public java.lang.String helloWorld(
        @WebParam(name = "name2", targetNamespace = "")
        java.lang.String name2
    );

    @WebMethod(operationName = "HelloSecret")
    @RequestWrapper(localName = "HelloSecret", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.HelloSecret")
    @ResponseWrapper(localName = "HelloSecretResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.HelloSecretResponse")
    @WebResult(name = "ElementsWrapper", targetNamespace = "")
    public pl.agh.edu.kis.HelloSecretResponse.ElementsWrapper helloSecret(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebMethod
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.GetStudentResponse")
    @WebResult(name = "studentGet", targetNamespace = "")
    public pl.agh.edu.kis.Student getStudent(
        @WebParam(name = "id", targetNamespace = "")
        int id
    );

    @WebMethod(operationName = "HelloStudent")
    @RequestWrapper(localName = "HelloStudent", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.HelloStudent")
    @ResponseWrapper(localName = "HelloStudentResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.HelloStudentResponse")
    @WebResult(name = "HelloStudent", targetNamespace = "")
    public pl.agh.edu.kis.Student helloStudent();

    @WebMethod
    @RequestWrapper(localName = "createStudent", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.CreateStudent")
    @ResponseWrapper(localName = "createStudentResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.agh.edu.kis.CreateStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String createStudent(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "surname", targetNamespace = "")
        java.lang.String surname,
        @WebParam(name = "avatar_filepath", targetNamespace = "")
        java.lang.String avatarFilepath,
        @WebParam(name = "subjects", targetNamespace = "")
        java.util.List<java.lang.String> subjects
    );
}
